:Author: SEP769 Group 8
:Email:
:Date: 28/05/2022
:Revision: 1
:License: GPL V3

= Project: SEP769 Project - Smart Energy Efficient Grow Light

Smart grow light which turns on between certain hours of the day when the natural sunlight is not strong enough for healthy plant growth. Light intensity is measured using a photo-resistor and compared against a threshold. Based on the threshold and the time of the day, the light will be turned on or off.

== Step 1: Installation
Please describe the steps to install this project.

Create an Arduino Cloud IoT "Thing" and then import the zipped code file into the Arduino Web Editor

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 SEP769_Project                => Arduino sketch folder
  ├── SEP769_Project.ino       => main Arduino file
  ├── thingProperties.h       => main Arduino file
  ├── utilityFunctions.h       => main Arduino file
  ├── utilityFunctions.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a GPL V3 License.

=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
