// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onLightOnThresholdChange();
void onScheduleChange();

int lightIntensity;
int lightOnThreshold;
int lightStatusInt;
CloudSchedule schedule;
bool lightStatus;

void initProperties(){

  ArduinoCloud.addProperty(lightIntensity, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(lightOnThreshold, READWRITE, ON_CHANGE, onLightOnThresholdChange);
  ArduinoCloud.addProperty(lightStatusInt, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(schedule, READWRITE, ON_CHANGE, onScheduleChange);
  ArduinoCloud.addProperty(lightStatus, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
